### use account
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 10000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "4cb8d1f819c54ab597a583434104a5b3",
  "accountNumber": "1000000001",
  "amount": 10000
}